export const SET_CHARACTERS = 'CHARACTERS/SET_CHARACTERS'
export const ADD_CHARACTER = 'CHARACTERS/ADD_CHARACTER'
export const REMOVE_CHARACTER = 'CHARACTERS/REMOVE_CHARACTER'
export const CHANGE_CHARACTER_NAME = 'CHARACTERS/CHANGE_NAME'

